config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'memes#index'
  get "/popular", to: "memes#popular"
  resources :memes, only: [:show, :new, :create] do
    resources :comments, only: :create
    resources :votes, only: :create
  end
  resources :categories, only: [:index]

  resources :memes, only: [:show] do
    resources :comments, only: [:create]
  end

  resources :users, only: [:index]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  # Associations
  has_many :memes

  # Validations
  validates :name, uniqueness: true, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :meme, counter_cache: true
end

app/models/meme.rb
# frozen_string_literal: true

class Meme < ApplicationRecord
  self.inheritance_column = :_ # Disable STI
  # Associations
  belongs_to :category
  belongs_to :owner, class_name: "User", counter_cache: true
  has_and_belongs_to_many :tags
  has_many :comments
  has_many :commentators, through: :comments, source: :user
  has_many :votes
  has_many :voters, through: :votes, source: :user

  # Enums
  enum type: { image: "image", gif: "gif" }

  # Validations
  validates :title, presence: true, uniqueness: true
  validates :type, presence: true
  validates :url_source, presence: true,
            format: {
              with: %r{\Ahttps?://.+(png|gif|jpg)\z},
              message: "Add a valid meme URL"
            }

  def has_voted?(user)
    votes.exists?(user: user)
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  # Associations
  has_and_belongs_to_many :memes

  # Validations
  validates :name, uniqueness: true, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Associations
  has_many :memes, foreign_key: :owner_id
  has_many :votes
  has_many :voted_memes, through: :votes, source: :meme
  has_many :comments
  has_many :commented_memes, through: :comments, source: :meme

  # Validations
  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
end

app/models/vote.rb
# votes_count
class Vote < ApplicationRecord
  # Associations
  belongs_to :meme, counter_cache: true
  belongs_to :user

  # Validations
  # meme, usuario
  validates_uniqueness_of :user_id, scope: :meme_id, message: "Can't vote a meme more than once"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/memes_controller.rb
# /popular
class MemesController < ApplicationController
  def index
    memes = Meme.all.order(created_at: :desc)
    @memes_by_date = memes.group_by { |meme| meme.created_at.to_date }
  end

  def show
    @meme = Meme.find(params[:id])
    @comment = Comment.new
  end

  def create
    @meme = current_user.memes.new(meme_params)
    if @meme.save
      redirect_to meme_path(@meme)
    else
      render "new"
    end
  end

  def new
    @meme = Meme.new
  end

  def popular
    @memes = Meme.all.order(votes_count: :desc)
  end

  private

  def meme_params
    params.require(:meme).permit(:title, :url_source, :type, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/memes_helper.rb
module MemesHelper
end

app/views/categories/index.html.erb
<% @categories.each do |category| %>
  <h2><%= category.name %></h2>

  <%= render partial: "memes/meme", collection: category.memes %>
<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Memeable</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

<main class="main-content">
  <header>
    <%= link_to root_path do %>
      <%= image_tag "memeable.png" %>
    <% end %>

    <nav>
      <%= link_to "By category", categories_path %>
      <%= link_to "By popularity", popular_path %>
      <%= link_to "Search", "" %>

      <% if user_signed_in? %>
        <%= link_to "Create meme", new_meme_path %>
        Welcome, <%= current_user.username %>
        <%= link_to "My Account", users_path %>
        <%= link_to "Logout", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to "Login", user_session_path %>
      <% end %>
    </nav>
  </header>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>
</main>

<footer class="signature">
  Made by Julio
</footer>

</body>
</html>

app/views/memes/_meme.html.erb
<%= link_to meme_path(meme) do %>
  <figure>
    <%= image_tag meme.url_source, alt: meme.title, width: "200px" %>
    <figcaption>Created by: <%= meme.owner.username %></figcaption>
  </figure>
<% end %>

app/views/memes/create.html.erb
<h1>Memes#create</h1>
<p>Find me in app/views/memes/create.html.erb</p>

app/views/memes/index.html.erb
<% @memes_by_date.each do |date, memes| %>
  <h2><%= date.strftime("%A, %b %-d") %></h2>

  <%= render partial: "meme", collection: memes %>
<% end %>

app/views/memes/new.html.erb
<h1>Create a meme!</h1>

<%= form_with model: @meme, local: true do |f| %>
  <ul>
    <% @meme.errors.full_messages.each do |message| %>
      <li>
        <%= message %>
      </li>
    <% end %>
  </ul>

  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :url_source %>
    <%= f.text_field :url_source %>
  </p>

  <p>
    <%= f.label :type %>
    <%= f.select :type, Meme.types %>
  </p>

  <p>
    <%= f.label :category_id %>
    <%= f.collection_select :category_id, Category.all, :id, :name %>
  </p>

  <%= f.submit "Create!" %>
<% end %>

app/views/memes/popular.html.erb
<h1>Most popular memes</h1>

<div class="memes-container">
  <%= render partial: "memes/meme", collection: @memes %>
</div>

app/views/memes/show.html.erb
<h1><%= @meme.title %></h1>

<%= image_tag @meme.url_source, alt: @meme.title, width: "400px" %>

<p>
  Category: <%= @meme.category.name %>
</p>

<div>
  Votes: <%= @meme.votes_count %>
  <% if user_signed_in? %>
    <% unless @meme.has_voted?(current_user) %>
      <%= button_to "Vote!", meme_votes_path(@meme), method: :post %>
    <% end %>
  <% else %>
    Login to vote!
  <% end %>
</div>

<div>
  <h2>Comments</h2>

  <% unless user_signed_in? %>
    <p>Login to add a comment!</p>
  <% end %>

  <%= form_for [@meme, @comment] do |f| %>
    <%= f.text_area :body %>
    <button>Comment!</button>
  <% end %>

  <ul>
    <% @meme.comments.each do |comment| %>
      <li><%= comment.user.username %>: <%= comment.body %></li>
    <% end %>
  </ul>
</div>